spring:
  #spring.main.allow-bean-definition-overriding=true
  #main:
  #allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/restserverfortest
    #url: jdbc:postgresql://localhost:5432/simple_spring_backend_db
    username: postgres
    password: "postgres"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        #spring.jpa.generate-ddl=true
        ddl-auto: update
        #ddl-auto: create-drop
        temp:
          use_jdbc_metadata_defaults: false
#security:
#  user:
#    password: password
#  ignored:
#    - "*.bundle.*"
logging:
  level:
    org.springframework.security: DEBUG
    ROOT: DEBUG
springdoc:
  show-actuator: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
app-config:
  hello-message: "This is default environment"